### ISSUE TITLE
Update to JuMP 0.22 so PartiallySeparableNLPModels update to NLPModels 0.18

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/ExpressionTreeForge.jl#38]
However, ExpressionTreeForge.jl depends for now of JuMP v0.21.5, I can try to update it to v0.22 if it blocks you to upgrade NLPModels.jl and NLPModelsJuMP. jl .

https://github.com/JuliaSmoothOptimizers/ExpressionTreeForge.jl/blob/752859910947ba907fded0b8158896f41d4a8ac1/Project.toml#L20

_Originally posted by @paraynaud in https://github.com/JuliaSmoothOptimizers/PartiallySeparableNLPModels.jl/issues/51#issuecomment-1209313018_

**Comment by paraynaud** [comment]
It will be solve soon!
